name: "Hello World Action"
description: "A simple composite action that prints a hello message"
inputs:
  message:
    description: "The message to print"
    required: false
    default: "Hello, World from pet-target!"
runs:
  using: "composite"
  steps:
    - name: Print the message
      shell: bash
      run: echo "${{ inputs.message }}"
